/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { awsModelPath } from "../../utils/awsModelPath";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    book_Cube030: THREE.Mesh;
    book_Cube030_1: THREE.Mesh;
    book_Cube030_2: THREE.Mesh;
    book_Cube030_3: THREE.Mesh;
    book_Cube030_4: THREE.Mesh;
    book_Cube030_5: THREE.Mesh;
    book_Cube030_6: THREE.Mesh;
    book_Cube030_7: THREE.Mesh;
    book_Cube030_8: THREE.Mesh;
    book_Cube030_9: THREE.Mesh;
    book_Cube030_10: THREE.Mesh;
    book_Cube030_11: THREE.Mesh;
  };
  materials: {
    bookpages: THREE.MeshStandardMaterial;
    bookbinding4: THREE.MeshStandardMaterial;
    bookbinding1: THREE.MeshStandardMaterial;
    bookbinding2: THREE.MeshStandardMaterial;
    bookbinding9: THREE.MeshStandardMaterial;
    bookbinding3: THREE.MeshStandardMaterial;
    bookbinding8: THREE.MeshStandardMaterial;
    bookbinding5: THREE.MeshStandardMaterial;
    bookbinding10: THREE.MeshStandardMaterial;
    bookbinding6: THREE.MeshStandardMaterial;
    bookImg: THREE.MeshStandardMaterial;
    bookbinding7: THREE.MeshStandardMaterial;
  };
};
let modelPath = "/models/books.gltf";
import.meta.env.PROD ? (modelPath = awsModelPath(modelPath)) : null;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(modelPath) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[1.36, 9.52, 22.48]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030.geometry}
          material={materials.bookpages}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_1.geometry}
          material={materials.bookbinding4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_2.geometry}
          material={materials.bookbinding1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_3.geometry}
          material={materials.bookbinding2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_4.geometry}
          material={materials.bookbinding9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_5.geometry}
          material={materials.bookbinding3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_6.geometry}
          material={materials.bookbinding8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_7.geometry}
          material={materials.bookbinding5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_8.geometry}
          material={materials.bookbinding10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_9.geometry}
          material={materials.bookbinding6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_10.geometry}
          material={materials.bookImg}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_Cube030_11.geometry}
          material={materials.bookbinding7}
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelPath);
