/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane003: THREE.Mesh;
    Plane003_1: THREE.Mesh;
    Plane003_2: THREE.Mesh;
  };
  materials: {
    bookShelfWood: THREE.MeshStandardMaterial;
    bookShelfBack: THREE.MeshStandardMaterial;
    bookShelfInner: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/bookshelf.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[1.92, 5.43, 22.89]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials.bookShelfWood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials.bookShelfBack}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials.bookShelfInner}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/bookshelf.gltf");
