/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    logHolder: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube006_1: THREE.Mesh;
    Circle006: THREE.Mesh;
    Circle006_1: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    BASE_Cube: THREE.Mesh;
    BASE_Cube_1: THREE.Mesh;
    BASE_Cube_2: THREE.Mesh;
    BASE_Cube_3: THREE.Mesh;
    BASE_Cube_4: THREE.Mesh;
    BASE_Cube_5: THREE.Mesh;
    BASE_Cube_6: THREE.Mesh;
    Lamp_Cylinder: THREE.Mesh;
    Lamp_Cylinder_1: THREE.Mesh;
    BASE_Cube001: THREE.Mesh;
    BASE_Cube001_1: THREE.Mesh;
    BASE_Cube001_2: THREE.Mesh;
    BASE_Cube001_3: THREE.Mesh;
    BASE_Cube001_4: THREE.Mesh;
    BASE_Cube001_5: THREE.Mesh;
    BASE_Cube001_6: THREE.Mesh;
    Lamp_Cylinder001: THREE.Mesh;
    Lamp_Cylinder001_1: THREE.Mesh;
    Circle007: THREE.Mesh;
    Circle007_1: THREE.Mesh;
    Circle007_2: THREE.Mesh;
    Circle007_3: THREE.Mesh;
    Circle007_4: THREE.Mesh;
    Circle007_5: THREE.Mesh;
    Circle007_6: THREE.Mesh;
    Circle007_7: THREE.Mesh;
    Circle007_8: THREE.Mesh;
    Circle007_9: THREE.Mesh;
    Circle007_10: THREE.Mesh;
    Circle007_11: THREE.Mesh;
    Circle007_12: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    rug: THREE.Mesh;
    book_Cube030: THREE.Mesh;
    book_Cube030_1: THREE.Mesh;
    book_Cube030_2: THREE.Mesh;
    book_Cube030_3: THREE.Mesh;
    book_Cube030_4: THREE.Mesh;
    book_Cube030_5: THREE.Mesh;
    book_Cube030_6: THREE.Mesh;
    book_Cube030_7: THREE.Mesh;
    book_Cube030_8: THREE.Mesh;
    book_Cube030_9: THREE.Mesh;
    book_Cube030_10: THREE.Mesh;
    book_Cube030_11: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cylinder031: THREE.Mesh;
    Cylinder031_1: THREE.Mesh;
    Leg_Cylinder009: THREE.Mesh;
    Leg_Cylinder009_1: THREE.Mesh;
    Leg_Cylinder009_2: THREE.Mesh;
    Leg_Cylinder009_3: THREE.Mesh;
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    Circle001_3: THREE.Mesh;
    coffetable: THREE.Mesh;
    Circle: THREE.Mesh;
    Circle_1: THREE.Mesh;
    sheetmusic: THREE.Mesh;
    sheetmusicstack: THREE.Mesh;
    BACK_Cube004: THREE.Mesh;
    BACK_Cube004_1: THREE.Mesh;
    BACK_Cube004_2: THREE.Mesh;
    BACK_Cube004_3: THREE.Mesh;
    Cylinder027: THREE.Mesh;
    Cylinder027_1: THREE.Mesh;
    Cylinder027_2: THREE.Mesh;
    Cylinder027_3: THREE.Mesh;
    Cylinder027_4: THREE.Mesh;
    Cylinder027_5: THREE.Mesh;
    Cylinder027_6: THREE.Mesh;
    Cylinder027_7: THREE.Mesh;
    Cylinder027_8: THREE.Mesh;
    Cylinder027_9: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane003_1: THREE.Mesh;
    Plane003_2: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane007_1: THREE.Mesh;
    Plane007_2: THREE.Mesh;
    ["uploads_files_2074012_034+-+Pendant+Light+2"]: THREE.Mesh;
    ["uploads_files_2074012_034+-+Pendant+Light+2_1"]: THREE.Mesh;
    ["uploads_files_2074012_034+-+Pendant+Light+2_2"]: THREE.Mesh;
    ["uploads_files_2074012_034+-+Pendant+Light+2_3"]: THREE.Mesh;
  };
  materials: {
    fpBlk: THREE.MeshStandardMaterial;
    ["lampMetal.001"]: THREE.MeshStandardMaterial;
    BRUSH: THREE.MeshStandardMaterial;
    black_paint: THREE.MeshStandardMaterial;
    bookbinding8: THREE.MeshStandardMaterial;
    standtop: THREE.MeshStandardMaterial;
    standlegs: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    None: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    lampLight: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    microrogi: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    usb: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    paintingImage1: THREE.MeshStandardMaterial;
    paintingWood: THREE.MeshPhysicalMaterial;
    blank: THREE.MeshStandardMaterial;
    rug: THREE.MeshStandardMaterial;
    bookpages: THREE.MeshStandardMaterial;
    bookbinding4: THREE.MeshStandardMaterial;
    bookbinding1: THREE.MeshStandardMaterial;
    bookbinding2: THREE.MeshStandardMaterial;
    bookbinding9: THREE.MeshStandardMaterial;
    bookbinding3: THREE.MeshStandardMaterial;
    bookbinding5: THREE.MeshStandardMaterial;
    bookbinding10: THREE.MeshStandardMaterial;
    bookbinding6: THREE.MeshStandardMaterial;
    bookImg: THREE.MeshStandardMaterial;
    bookbinding7: THREE.MeshStandardMaterial;
    paintingImage2: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    couchbrown: THREE.MeshStandardMaterial;
    couchgreen: THREE.MeshStandardMaterial;
    couchbrtop: THREE.MeshStandardMaterial;
    goggleLens: THREE.MeshStandardMaterial;
    swimCap: THREE.MeshStandardMaterial;
    speedologo: THREE.MeshStandardMaterial;
    tabletop: THREE.MeshStandardMaterial;
    frisbeeOutline: THREE.MeshStandardMaterial;
    frisbeeCenter: THREE.MeshStandardMaterial;
    sheetmusic: THREE.MeshStandardMaterial;
    skibindingROD: THREE.MeshStandardMaterial;
    skibindingbase: THREE.MeshStandardMaterial;
    skibindingFRONT2: THREE.MeshStandardMaterial;
    skiLogo: THREE.MeshStandardMaterial;
    ["metal.002"]: THREE.MeshStandardMaterial;
    ["pickguard.001"]: THREE.MeshStandardMaterial;
    ["mahogany.001"]: THREE.MeshStandardMaterial;
    ["top.001"]: THREE.MeshStandardMaterial;
    guitarinside: THREE.MeshStandardMaterial;
    ["metal.003"]: THREE.MeshStandardMaterial;
    ["text.001"]: THREE.MeshStandardMaterial;
    ["fretboard.001"]: THREE.MeshStandardMaterial;
    bookShelfWood: THREE.MeshStandardMaterial;
    bookShelfBack: THREE.MeshStandardMaterial;
    bookShelfInner: THREE.MeshStandardMaterial;
    lampfabric: THREE.MeshStandardMaterial;
    lampWood: THREE.MeshStandardMaterial;
    lampWire: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

let path = "/models/furniture.gltf";
if (import.meta.env.PROD) {
  path = "";
  // update to AWS s3 bucket
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(path) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.logHolder.geometry}
        material={materials.fpBlk}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["lampMetal.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006_1.geometry}
        material={materials.BRUSH}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials.black_paint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006_1.geometry}
        material={materials.bookbinding8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.standtop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002_1.geometry}
        material={materials.standlegs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube.geometry}
        material={materials["Material.012"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube_1.geometry}
        material={materials["Material.013"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube_2.geometry}
        material={materials["Material.014"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube_3.geometry}
        material={materials["Material.015"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube_4.geometry}
        material={materials.None}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube_5.geometry}
        material={materials["Material.016"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube_6.geometry}
        material={materials["Material.017"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp_Cylinder.geometry}
        material={materials.lampLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp_Cylinder_1.geometry}
        material={materials["lampMetal.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube001.geometry}
        material={materials["Material.012"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube001_1.geometry}
        material={materials["Material.013"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube001_2.geometry}
        material={materials["Material.014"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube001_3.geometry}
        material={materials["Material.015"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube001_4.geometry}
        material={materials.None}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube001_5.geometry}
        material={materials["Material.016"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BASE_Cube001_6.geometry}
        material={materials["Material.017"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp_Cylinder001.geometry}
        material={materials.lampLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp_Cylinder001_1.geometry}
        material={materials["lampMetal.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials["Material.009"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_1.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_2.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_3.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_4.geometry}
        material={materials.microrogi}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_5.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_6.geometry}
        material={materials.usb}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_7.geometry}
        material={materials["Material.007"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_8.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_9.geometry}
        material={materials["Material.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_10.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_11.geometry}
        material={materials["Material.010"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007_12.geometry}
        material={materials["Material.011"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.paintingImage1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_1.geometry}
        material={materials.paintingWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_2.geometry}
        material={materials.blank}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rug.geometry}
        material={materials.rug}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030.geometry}
        material={materials.bookpages}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_1.geometry}
        material={materials.bookbinding4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_2.geometry}
        material={materials.bookbinding1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_3.geometry}
        material={materials.bookbinding2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_4.geometry}
        material={materials.bookbinding9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_5.geometry}
        material={materials.bookbinding3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_6.geometry}
        material={materials.bookbinding8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_7.geometry}
        material={materials.bookbinding5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_8.geometry}
        material={materials.bookbinding10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_9.geometry}
        material={materials.bookbinding6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_10.geometry}
        material={materials.bookImg}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book_Cube030_11.geometry}
        material={materials.bookbinding7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.paintingImage2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_1.geometry}
        material={materials.black_paint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={materials.wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031_1.geometry}
        material={materials["lampMetal.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_Cylinder009.geometry}
        material={materials.couchbrown}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_Cylinder009_1.geometry}
        material={materials.couchgreen}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_Cylinder009_2.geometry}
        material={materials.wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg_Cylinder009_3.geometry}
        material={materials.couchbrtop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials.black_paint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_1.geometry}
        material={materials.goggleLens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_2.geometry}
        material={materials.swimCap}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_3.geometry}
        material={materials.speedologo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.coffetable.geometry}
        material={materials.tabletop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials.frisbeeOutline}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_1.geometry}
        material={materials.frisbeeCenter}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sheetmusic.geometry}
        material={materials.sheetmusic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sheetmusicstack.geometry}
        material={materials.sheetmusic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_Cube004.geometry}
        material={materials.skibindingROD}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_Cube004_1.geometry}
        material={materials.skibindingbase}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_Cube004_2.geometry}
        material={materials.skibindingFRONT2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_Cube004_3.geometry}
        material={materials.skiLogo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={materials["metal.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_1.geometry}
        material={materials["pickguard.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_2.geometry}
        material={materials["mahogany.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_3.geometry}
        material={materials["top.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_4.geometry}
        material={materials.black_paint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_5.geometry}
        material={materials.blank}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_6.geometry}
        material={materials.guitarinside}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_7.geometry}
        material={materials["metal.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_8.geometry}
        material={materials["text.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027_9.geometry}
        material={materials["fretboard.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.bookShelfWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003_1.geometry}
        material={materials.bookShelfBack}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003_2.geometry}
        material={materials.bookShelfInner}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.bookShelfWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007_1.geometry}
        material={materials.bookShelfInner}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007_2.geometry}
        material={materials.bookShelfBack}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["uploads_files_2074012_034+-+Pendant+Light+2"].geometry}
        material={materials.lampfabric}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["uploads_files_2074012_034+-+Pendant+Light+2_1"].geometry
        }
        material={materials.lampWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["uploads_files_2074012_034+-+Pendant+Light+2_2"].geometry
        }
        material={materials.lampWire}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["uploads_files_2074012_034+-+Pendant+Light+2_3"].geometry
        }
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload(path);
