/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    lightswitch: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube001_2: THREE.Mesh;
    Laptop_Cube009: THREE.Mesh;
    Laptop_Cube009_1: THREE.Mesh;
    Laptop_Cube009_2: THREE.Mesh;
    Laptop_Cube009_3: THREE.Mesh;
    logs: THREE.Mesh;
  };
  materials: {
    Black_Switch: THREE.MeshStandardMaterial;
    black_paint: THREE.MeshStandardMaterial;
    goggleLens: THREE.MeshStandardMaterial;
    blank: THREE.MeshStandardMaterial;
    Buttons: THREE.MeshStandardMaterial;
    proj: THREE.MeshStandardMaterial;
    lens: THREE.MeshStandardMaterial;
    Def: THREE.MeshStandardMaterial;
    Scerrn: THREE.MeshStandardMaterial;
    laptopScreen: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
  };
};

let path = "/models/interact.gltf";
if (import.meta.env.PROD) {
  path = "";
  // update to AWS s3 bucket
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(path) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.lightswitch.geometry}
        material={materials.Black_Switch}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.black_paint}
      />
      <mesh
        geometry={nodes.Cylinder_1.geometry}
        material={materials.goggleLens}
      />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.blank} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Buttons} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.proj} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials.lens} />
      <mesh
        geometry={nodes.Laptop_Cube009.geometry}
        material={materials.Buttons}
      />
      <mesh
        geometry={nodes.Laptop_Cube009_1.geometry}
        material={materials.Def}
      />
      <mesh
        geometry={nodes.Laptop_Cube009_2.geometry}
        material={materials.Scerrn}
      />
      <mesh
        geometry={nodes.Laptop_Cube009_3.geometry}
        material={materials.laptopScreen}
      />
      <mesh geometry={nodes.logs.geometry} material={materials.wood} />
    </group>
  );
}

useGLTF.preload(path);
