/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useRef } from "react";
import { Select } from "@react-three/postprocessing";
import { awsModelPath } from "../../utils/awsModelPath";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Laptop_Cube009: THREE.Mesh;
    Laptop_Cube009_1: THREE.Mesh;
    Laptop_Cube009_2: THREE.Mesh;
    Laptop_Cube009_3: THREE.Mesh;
  };
  materials: {
    Buttons: THREE.MeshStandardMaterial;
    Def: THREE.MeshStandardMaterial;
    Scerrn: THREE.MeshStandardMaterial;
    laptopScreen: THREE.MeshStandardMaterial;
  };
};
let modelPath: string = "/models/laptop.gltf";
import.meta.env.PROD ? (modelPath = awsModelPath(modelPath)) : null;
export function Model(props: JSX.IntrinsicElements["group"]) {
  const ref = useRef<THREE.Mesh>(null!);
  const { nodes, materials } = useGLTF(modelPath) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[25.85, 3.44, 11.71]}>
        {/* base */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laptop_Cube009_1.geometry}
          material={materials.Def}
        />

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Laptop_Cube009_2.geometry}
          material={materials.Scerrn}
        />
        <Select enabled>
          <mesh
            ref={ref}
            castShadow
            receiveShadow
            geometry={nodes.Laptop_Cube009_3.geometry}
            material={materials.laptopScreen}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Laptop_Cube009.geometry}
            material={materials.Buttons}
          />
        </Select>
      </group>
    </group>
  );
}

useGLTF.preload(modelPath);
