/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { awsModelPath } from "../../utils/awsModelPath";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle006: THREE.Mesh;
    Circle006_1: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane002_1: THREE.Mesh;
    Plane002_2: THREE.Mesh;
    Cylinder027: THREE.Mesh;
    Cylinder027_1: THREE.Mesh;
    Cylinder027_2: THREE.Mesh;
    Cylinder027_3: THREE.Mesh;
    Cylinder027_4: THREE.Mesh;
    Cylinder027_5: THREE.Mesh;
    Cylinder027_6: THREE.Mesh;
    Cylinder027_7: THREE.Mesh;
    Cylinder027_8: THREE.Mesh;
    Cylinder027_9: THREE.Mesh;
  };
  materials: {
    black_paint: THREE.MeshStandardMaterial;
    bookbinding8: THREE.MeshStandardMaterial;
    sheetmusic: THREE.MeshStandardMaterial;
    standtop: THREE.MeshStandardMaterial;
    standlegs: THREE.MeshStandardMaterial;
    ["metal.002"]: THREE.MeshStandardMaterial;
    ["pickguard.001"]: THREE.MeshStandardMaterial;
    ["mahogany.001"]: THREE.MeshStandardMaterial;
    ["top.001"]: THREE.MeshStandardMaterial;
    blank: THREE.MeshStandardMaterial;
    guitarinside: THREE.MeshStandardMaterial;
    ["metal.003"]: THREE.MeshStandardMaterial;
    ["text.001"]: THREE.MeshStandardMaterial;
    ["fretboard.001"]: THREE.MeshStandardMaterial;
  };
};
let modelPath: string = "/models/guitar_and_music.gltf";
import.meta.env.PROD ? (modelPath = awsModelPath(modelPath)) : null;
export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(modelPath) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[38.21, 1.96, 32.84]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006.geometry}
          material={materials.black_paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_1.geometry}
          material={materials.bookbinding8}
        />
      </group>
      <group position={[0, 0.05, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.sheetmusic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.standtop}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials.standlegs}
        />
      </group>
      <group position={[37.8, 4.44, 32.56]} rotation={[-0.09, -0.1, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027.geometry}
          material={materials["metal.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_1.geometry}
          material={materials["pickguard.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_2.geometry}
          material={materials["mahogany.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_3.geometry}
          material={materials["top.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_4.geometry}
          material={materials.black_paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_5.geometry}
          material={materials.blank}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_6.geometry}
          material={materials.guitarinside}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_7.geometry}
          material={materials["metal.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_8.geometry}
          material={materials["text.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_9.geometry}
          material={materials["fretboard.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelPath);
