/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube015_1: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube_1: THREE.Mesh;
  };
  materials: {
    bookbinding7: THREE.MeshStandardMaterial;
    photoImg1: THREE.MeshStandardMaterial;
    bookbinding1: THREE.MeshStandardMaterial;
    photoImg2: THREE.MeshStandardMaterial;
    ["text.001"]: THREE.MeshStandardMaterial;
    photoImg3: THREE.MeshStandardMaterial;
    ["metal.003"]: THREE.MeshStandardMaterial;
    photoImg4: THREE.MeshStandardMaterial;
    bookbinding2: THREE.MeshStandardMaterial;
    photoImg5: THREE.MeshStandardMaterial;
    bookbinding3: THREE.MeshStandardMaterial;
    photoImg6: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    photoImg7: THREE.MeshStandardMaterial;
    photoImg0: THREE.MeshStandardMaterial;
  };
};

let path = "/models/photos.gltf";
if (import.meta.env.PROD) {
  path = "";
  // update to AWS s3 bucket
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(path) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.bookbinding7}
      />
      <mesh
        geometry={nodes.Cube009_1.geometry}
        material={materials.photoImg1}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.bookbinding1}
      />
      <mesh
        geometry={nodes.Cube010_1.geometry}
        material={materials.photoImg2}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["text.001"]}
      />
      <mesh
        geometry={nodes.Cube011_1.geometry}
        material={materials.photoImg3}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["metal.003"]}
      />
      <mesh
        geometry={nodes.Cube014_1.geometry}
        material={materials.photoImg4}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials.bookbinding2}
      />
      <mesh
        geometry={nodes.Cube015_1.geometry}
        material={materials.photoImg5}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials.bookbinding3}
      />
      <mesh
        geometry={nodes.Cube016_1.geometry}
        material={materials.photoImg6}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        geometry={nodes.Cube017_1.geometry}
        material={materials.photoImg7}
      />
      <mesh geometry={nodes.Cube.geometry} material={materials.photoImg0} />
      <mesh
        geometry={nodes.Cube_1.geometry}
        material={materials.bookbinding1}
      />
    </group>
  );
}

useGLTF.preload(path);
