/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane008: THREE.Mesh;
    Plane008_1: THREE.Mesh;
    Plane008_2: THREE.Mesh;
    Plane008_3: THREE.Mesh;
    Plane008_4: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube013_2: THREE.Mesh;
  };
  materials: {
    brick: THREE.MeshStandardMaterial;
    woodbeam: THREE.MeshStandardMaterial;
    wallWood: THREE.MeshStandardMaterial;
    fpstone2: THREE.MeshStandardMaterial;
    woodpanel: THREE.MeshStandardMaterial;
    fpstone1: THREE.MeshStandardMaterial;
    fpBlk: THREE.MeshStandardMaterial;
  };
};

let path = "/models/room.gltf";
if (import.meta.env.PROD) {
  path = "";
  // update to AWS s3 bucket
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(path) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane008.geometry} material={materials.brick} />
      <mesh
        geometry={nodes.Plane008_1.geometry}
        material={materials.woodbeam}
      />
      <mesh
        geometry={nodes.Plane008_2.geometry}
        material={materials.wallWood}
      />
      <mesh
        geometry={nodes.Plane008_3.geometry}
        material={materials.fpstone2}
      />
      <mesh
        geometry={nodes.Plane008_4.geometry}
        material={materials.woodpanel}
      />
      <mesh geometry={nodes.Cube013.geometry} material={materials.fpstone1} />
      <mesh geometry={nodes.Cube013_1.geometry} material={materials.fpBlk} />
      <mesh geometry={nodes.Cube013_2.geometry} material={materials.fpstone2} />
    </group>
  );
}

useGLTF.preload(path);
