/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BACK_Cube004: THREE.Mesh;
    BACK_Cube004_1: THREE.Mesh;
    BACK_Cube004_2: THREE.Mesh;
    BACK_Cube004_3: THREE.Mesh;
  };
  materials: {
    skibindingROD: THREE.MeshStandardMaterial;
    skibindingbase: THREE.MeshStandardMaterial;
    skibindingFRONT2: THREE.MeshStandardMaterial;
    skiLogo: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/skis.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[40.63, 5.41, 22.71]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BACK_Cube004.geometry}
          material={materials.skibindingROD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BACK_Cube004_1.geometry}
          material={materials.skibindingbase}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BACK_Cube004_2.geometry}
          material={materials.skibindingFRONT2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BACK_Cube004_3.geometry}
          material={materials.skiLogo}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/skis.gltf");
